global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'product-categorizer-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['api:5000']
    metrics_path: '/api/metrics'

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']